version: "3.9"

services:
  php:
    container_name: ${PROJECT_NAME:-solo}-${SERVICE_NAME:-service}-api-${API_VERSION:-1.0}-php-${APP_ENV:-local}
    env_file:
      - .env
      - .env.local
      
  web:
    container_name: ${PROJECT_NAME:-solo}-${SERVICE_NAME:-service}-api-${API_VERSION:-1.0}-web-${APP_ENV:-local}
    env_file:
      - .env
      - .env.local
