version: "3.9"

services:
  php:
    container_name: ${PROJECT_NAME:-solo}-${SERVICE_NAME:-service}-api-${API_VERSION:-1.0}-php-${APP_ENV:-local}
    env_file:
      - .env
      - .env.local
      
  web:
    container_name: ${PROJECT_NAME:-solo}-${SERVICE_NAME:-service}-api-${API_VERSION:-1.0}-web-${APP_ENV:-local}
    env_file:
      - .env
      - .env.local
    labels:
      - "traefik.http.routers.${PROJECT_NAME}-${SERVICE_NAME}-http.rule=Host(`saas.localhost`) && PathPrefix(`/${SERVICE_NAME}/api/v${API_VERSION}`, `/${SERVICE_NAME}/_profiler`)"
      - "traefik.http.routers.${PROJECT_NAME}-${SERVICE_NAME}-https.rule=Host(`saas.localhost`) && PathPrefix(`/${SERVICE_NAME}/api/v${API_VERSION}`, `/${SERVICE_NAME}/_profiler`)"
      - "traefik.http.routers.${PROJECT_NAME}-${SERVICE_NAME}-https.tls.domains[0].main=saas.localhost"
